# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_proposals', '0001_initial'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSpaceProposal',
            fields=[
                ('proposalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='symposion_proposals.ProposalBase')),
            ],
            bases=('symposion_proposals.proposalbase',),
        ),
        migrations.CreateModel(
            name='TutorialProposal',
            fields=[
                ('proposalbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='symposion_proposals.ProposalBase')),
                ('audience_level', models.IntegerField(choices=[(1, b'Novice'), (3, b'Intermediate'), (2, b'Experienced'), (4, b'Not Applicable')])),
                ('recording_release', models.BooleanField(default=True, help_text='By submitting your talk proposal, you agree to give permission to the conference organizers to record, edit, and release audio and/or video of your presentation. If you do not agree to this, please uncheck this box.')),
                ('special_requirements', markitup.fields.MarkupField(blank=True, help_text='If you have any special requirements such as needing travel assistance, accessibility needs, or anything else please let us know here so that  we may plan accordingly. (This is not made public nor will the review committee have access to view it.)', no_rendered_field=True, verbose_name='Special Requirements')),
                ('_special_requirements_rendered', models.TextField(blank=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('symposion_proposals.proposalbase',),
        ),
        migrations.AlterModelOptions(
            name='talkproposal',
            options={},
        ),
        migrations.AddField(
            model_name='talkproposal',
            name='_special_requirements_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='talkproposal',
            name='special_requirements',
            field=markitup.fields.MarkupField(blank=True, help_text='If you have any special requirements such as needing travel assistance, accessibility needs, or anything else please let us know here so that  we may plan accordingly. (This is not made public nor will the review committee have access to view it.)', no_rendered_field=True, verbose_name='Special Requirements'),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='audience_level',
            field=models.IntegerField(choices=[(1, b'Novice'), (3, b'Intermediate'), (2, b'Experienced'), (4, b'Not Applicable')]),
        ),
        migrations.AlterField(
            model_name='talkproposal',
            name='recording_release',
            field=models.BooleanField(default=True, help_text='By submitting your talk proposal, you agree to give permission to the conference organizers to record, edit, and release audio and/or video of your presentation. If you do not agree to this, please uncheck this box.'),
        ),
    ]
