# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20160229_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='audience_level',
            field=models.IntegerField(choices=[(1, b'Novice'), (3, b'Intermediate or Advanced'), (4, b'Not Applicable')]),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='audience_level',
            field=models.IntegerField(choices=[(1, b'Novice'), (3, b'Intermediate or Advanced'), (4, b'Not Applicable')]),
        ),
    ]
